//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVIDAD()
        {
            this.ACTIVIDADAPORTES = new HashSet<ACTIVIDADAPORTES>();
        }
    
        public decimal IDACTIVIDAD { get; set; }
        public decimal IDTIPOACTIVIDAD { get; set; }
        public decimal IDCURSO { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual TIPOACTIVIDAD TIPOACTIVIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIVIDADAPORTES> ACTIVIDADAPORTES { get; set; }
    }
}
