//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDADAPORTES
    {
        public decimal ACTIVIDAD { get; set; }
        public decimal CUENTAALUMNOS { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public decimal APORTE { get; set; }
    }
}
