//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALUMNO()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
            this.CUENTAALUMNO = new HashSet<CUENTAALUMNO>();
            this.POLIZASEGURO = new HashSet<POLIZASEGURO>();
        }
    
        public decimal IDALUMNO { get; set; }
        public decimal IDAPODERADO { get; set; }
        public decimal IDCURSO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCIÓN { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string CORREOELECTRONICO { get; set; }
    
        public virtual APODERADO APODERADO { get; set; }
        public virtual CURSO CURSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUENTAALUMNO> CUENTAALUMNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLIZASEGURO> POLIZASEGURO { get; set; }
    }
}
