//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public decimal IDALUMNO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public decimal APODERADO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string CORREOELECTRONICO { get; set; }
        public decimal CURSO { get; set; }
    }
}
