//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public decimal IDCONTRATO { get; set; }
        public decimal TIPOCONTRATO { get; set; }
        public decimal VENDEDOR { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHATERMINO { get; set; }
        public decimal ALUMNO { get; set; }
        public decimal GARANTIA { get; set; }
    }
}
