//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTAALUMNO
    {
        public decimal IDCUENTAALUMNOS { get; set; }
        public Nullable<decimal> CUPOTOTAL { get; set; }
        public Nullable<decimal> CUPOUTILIZADO { get; set; }
        public decimal TIPOCUENTA { get; set; }
        public decimal ALUMNO { get; set; }
        public decimal APORTE { get; set; }
        public Nullable<decimal> SALDO { get; set; }
    }
}
