//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOCUENTA
    {
        public decimal IDESTADOCUENTA { get; set; }
        public decimal CUENTAALUMNO { get; set; }
        public string DETALLE { get; set; }
    }
}
