//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINERARIO
    {
        public decimal IDDESTINO { get; set; }
        public decimal IDORIGEN { get; set; }
        public decimal IDACTIVIDADVIAJE { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHATERMINO { get; set; }
        public decimal IDCONTRATO { get; set; }
    
        public virtual ACTIVIDADVIAJE ACTIVIDADVIAJE { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual DESTINO DESTINO { get; set; }
        public virtual ORIGEN ORIGEN { get; set; }
    }
}
