//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_OnTour
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLIZASEGURO
    {
        public decimal IDPOLIZASEGURO { get; set; }
        public Nullable<decimal> DESCRIPCION { get; set; }
        public decimal TIPOSEGURO { get; set; }
        public decimal ASEGURADORA { get; set; }
        public decimal ALUMNO { get; set; }
        public Nullable<System.DateTime> VIGENCIAINICIO { get; set; }
        public Nullable<System.DateTime> VIGENCIATERMINO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATACION { get; set; }
        public Nullable<decimal> MONTOASEGURADO { get; set; }
    }
}
