//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_Agencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLABORADOR()
        {
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public decimal IDCOLABORADOR { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public decimal IDCUENTAUSUARIO { get; set; }
        public decimal IDTIPOCOLABORADOR { get; set; }
        public string RUT { get; set; }
    
        public virtual TIPOCOLABORADOR TIPOCOLABORADOR { get; set; }
        public virtual CUENTAUSUARIO CUENTAUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    }
}
