//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_Agencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public decimal IDMENU { get; set; }
        public decimal IDPERFIL { get; set; }
        public string NOMBREMENU { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
    }
}
