//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITravel_OnTour.Models.ORM_Agencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public decimal IDPAGO { get; set; }
        public decimal IDTIPOPAGO { get; set; }
        public decimal IDCUENTACURSO { get; set; }
        public decimal IDCUENTAALUMNO { get; set; }
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
        public string DETALLE { get; set; }
        public Nullable<decimal> MONTOCANCELADO { get; set; }
    
        public virtual CUENTAALUMNO CUENTAALUMNO { get; set; }
        public virtual CUENTACURSO CUENTACURSO { get; set; }
        public virtual TIPOPAGO TIPOPAGO { get; set; }
    }
}
